# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra", "~> 2.0"

gem "thin", "~> 1.7"

gem "zipkin-tracer", "~> 0.30.0"

gem "sidekiq", "~> 5.2"
